### ISSUE TITLE
How to report possible security issues?

### ISSUE THREAD

**Issue by roytanck** [wpwhitesecurity/wp-2fa#16]
For the past two weeks, I've been trying to contact WP White Security about a couple of potential issues. So far, I've gotten zero response. There's no RD info on your website as far as I can tell.

Is there an email address I can use to send you our findings? Any other way of communicating you prefer?

Thank you.

**Comment by robert81** [comment]
Hello @roytanck 

Sorry for not seeing this before. We only use this repo to copy the final version of the plugin. Please send me an email with all the details at robert@wpwhitesecurity.com. I look forward to hearing from you.
