### ISSUE TITLE
Problems with deployed version of code on WordPress.org

### ISSUE THREAD

**Issue by EliW** [wpwhitesecurity/wp-2fa#48]
It would appear that these two lines: (an oddly blank php statement)
https://github.com/wpwhitesecurity/wp-2fa/blob/582dadb9306db3fd14222f7206d1726ce46add80/includes/classes/Admin/Views/class-first-time-wizard-steps.php#L108-L109

In the deployed version are being collapsed into a line that is just:
`<?php?>`

Which causes a `Undefined constant` error to be thrown.

**Comment by robert81** [comment]
Obsolete.
